# Generated by Django 3.1.1 on 2020-09-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0002_link_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='last_visitet',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
