# Generated by Django 3.1.1 on 2020-09-14 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0003_link_last_visitet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='last_visitet',
            new_name='last_visited',
        ),
    ]
